import { FormEvent, useState } from 'react';
import { Avatar, Badge, Button, Card, Input, Logo } from './atoms';
import { FormField, PasswordCriteria, PasswordField } from './molecules';

export function LoginForm({ onSubmit, error, loading = false }: { onSubmit: (data: { email: string; password: string }) => void; error?: string; loading?: boolean }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  function submit(event: FormEvent) { event.preventDefault(); onSubmit({ email, password }); }
  return <form className="u-form" onSubmit={submit}><FormField id="login-email" name="email" label="E-mail" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" /><PasswordField id="login-password" name="password" label="Senha" value={password} onChange={(event) => setPassword(event.target.value)} required autoComplete="current-password" /><label className="u-check"><input type="checkbox" name="remember" /> Manter-me conectado</label><Button type="submit" loading={loading} disabled={loading}>{loading ? 'Aguarde...' : 'Entrar'}</Button>{error && <p className="u-error" role="alert">{error}</p>}</form>;
}

export function RegisterForm({ onSubmit, error, loading = false }: { onSubmit: (data: { name: string; email: string; password: string; confirmPassword: string }) => void; error?: string; loading?: boolean }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [confirmError, setConfirmError] = useState('');
  function submit(event: FormEvent) { event.preventDefault(); if (password !== confirmPassword) { setConfirmError('As senhas nao coincidem.'); return; } setConfirmError(''); onSubmit({ name, email, password, confirmPassword }); }
  return <form className="u-form" onSubmit={submit}><FormField id="register-name" name="name" label="Nome completo" value={name} onChange={(event) => setName(event.target.value)} required autoComplete="name" /><FormField id="register-email" name="email" label="E-mail" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" /><PasswordField id="register-password" name="password" label="Senha" value={password} onChange={(event) => setPassword(event.target.value)} required autoComplete="new-password" /><PasswordCriteria value={password} /><PasswordField id="register-confirm-password" name="confirmPassword" label="Confirmar senha" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} error={confirmError} required autoComplete="new-password" /><Button type="submit" loading={loading} disabled={loading}>{loading ? 'Aguarde...' : 'Criar conta'}</Button>{error && <p className="u-error" role="alert">{error}</p>}</form>;
}

export function AuthBrandPanel({ title = 'Construa o proximo passo da sua jornada.', description = 'Transforme ideias em projetos e cresca em comunidade.' }: { title?: string; description?: string }) { return <section className="u-brand" aria-label="Sobre a UniLaunch"><div className="u-brand-mark">U</div><p className="u-eyebrow">UNILAUNCH</p><h1>{title}</h1><p>{description}</p><div className="u-brand-line" /></section>; }

export function Topbar({ userName = 'Usuario', onLogout }: { userName?: string; onLogout: () => void }) { return <header className="u-topbar"><Logo /><div className="u-topbar-actions"><span>{userName}</span><Avatar name={userName} size="small" /><button type="button" onClick={onLogout}>Sair</button></div></header>; }

export function Sidebar({ active, items, onNavigate }: { active?: string; items: { label: string; href: string }[]; onNavigate?: (href: string) => void }) { return <nav className="u-sidebar" aria-label="Navegacao principal">{items.map((item) => <a key={item.href} className={active === item.href ? 'is-active' : ''} href={item.href} onClick={(event) => { if (onNavigate) { event.preventDefault(); onNavigate(item.href); } }}>{item.label}</a>)}</nav>; }

export function KanbanBoard({ columns, onMoveTask }: { columns: { id: string; title: string; tasks: { id: string; title: string; assignee?: string; status?: string }[] }[]; onMoveTask?: (taskId: string, columnId: string) => void }) { const [draggedTask, setDraggedTask] = useState<string | null>(null); return <div className="u-board">{columns.map((column) => <section className="u-board-column" key={column.id} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggedTask) onMoveTask?.(draggedTask, column.id); setDraggedTask(null); }}><h2>{column.title}</h2>{column.tasks.map((task) => <Card key={task.id}><article draggable={Boolean(onMoveTask)} onDragStart={() => setDraggedTask(task.id)} onDragEnd={() => setDraggedTask(null)}><strong>{task.title}</strong>{task.assignee && <small>{task.assignee}</small>}{task.status && <Badge text={task.status} tone="accent" />}</article></Card>)}</section>)}</div>; }

export function ProfileHeader({ name, bio, email, src, onEdit }: { name: string; bio?: string; email?: string; src?: string; onEdit: () => void }) { return <section className="u-profile"><Avatar name={name} src={src} size="large" /><div><h1>{name}</h1>{bio && <p>{bio}</p>}{email && <small>{email}</small>}</div><Button variant="ghost" onClick={onEdit}>Editar perfil</Button></section>; }

export function FeedPost({ author, content, time, likes = 0, onComment }: { author: string; content: string; time: string; likes?: number; onComment: () => void }) { return <Card><article className="u-feed-post"><header><Avatar name={author} size="small" /><div><strong>{author}</strong><time>{time}</time></div></header><p>{content}</p><footer><span>{likes} curtidas</span><button type="button" onClick={onComment}>Comentar</button></footer></article></Card>; }

export function NotificationList({ notifications }: { notifications: { id: string; title: string; time: string; read?: boolean }[] }) { return <div className="u-notifications">{notifications.map((notification) => <Card key={notification.id}><article className={!notification.read ? 'is-unread' : ''}><strong>{notification.title}</strong><time>{notification.time}</time></article></Card>)}</div>; }

export function AppShell({ active, items, userName, onLogout, children }: { active?: string; items: { label: string; href: string }[]; userName?: string; onLogout: () => void; children: ReactNode }) { return <div className="u-app-shell"><Topbar userName={userName} onLogout={onLogout} /><div className="u-app-body"><Sidebar active={active} items={items} /><main>{children}</main></div></div>; }
