name: Feature request
description: Propor uma melhoria ou nova funcionalidade
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Que necessidade esta proposta resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Descreva a solução desejada.
    validations:
      required: true
