"""create boards table

Revision ID: e483311a59d2
Revises: 0007_normalize_student_leads
Create Date: 2026-09-27 23:35:47.907394
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e483311a59d2"
down_revision: Union[str, Sequence[str], None] = "0007_normalize_student_leads"
branch_labels: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boards_owner_id"), "boards", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_boards_owner_id"), table_name="boards")
    op.drop_table("boards")
    # ### end Alembic commands ###
